import React from 'react';
import { BookOpen, ShieldCheck, Activity } from 'lucide-react';

export const AboutPage: React.FC = () => {
  return (
    <div className="about-page">
      <div className="page-header">
        <p className="eyebrow">Methodology</p>
        <h1>How the Estimator Works</h1>
        <p className="page-subtitle">
          We use industry-standard software engineering models to translate abstract diagrams into concrete effort.
        </p>
      </div>

      <div className="about-content">
        <section className="about-section model-card">
           <div className="model-header">
             <div className="icon-box">
                <BookOpen size={28} />
             </div>
             <h2>Use Case Points (UCP) Model</h2>
           </div>
          <div className="model-body">
            <p>
              The Use Case Points method is a software estimation technique used to forecast the software size for software development projects.
              It relies on the number and complexity of use cases and actors.
            </p>
            <ul>
              <li><strong>Unadjusted Use Case Weight (UUCW):</strong> Calculated from the number of transactions per use case.</li>
              <li><strong>Unadjusted Actor Weight (UAW):</strong> Calculated from the complexity of actors interacting with the system.</li>
              <li><strong>Technical Complexity Factor (TCF):</strong> Adjusts the estimate based on 13 non-functional requirements (e.g., performance, security).</li>
              <li><strong>Environmental Complexity Factor (ECF):</strong> Adjusts the estimate based on 8 team and project factors (e.g., experience, motivation).</li>
            </ul>
            <p className="equation">
              <code>UCP = (UUCW + UAW) × TCF × ECF</code>
            </p>
          </div>
        </section>

        <section className="about-section model-card">
           <div className="model-header">
             <div className="icon-box">
                <Activity size={28} />
             </div>
             <h2>Class Diagram Weight Model</h2>
           </div>
          <div className="model-body">
            <p>
              When a Class Diagram is provided, the estimator analyzes the static structure of the system to infer complexity.
            </p>
            <ul>
              <li><strong>Class Complexity:</strong> Evaluates the number of attributes and methods per class.</li>
              <li><strong>Relationship Density:</strong> Measures the number of associations, inheritances, and dependencies between classes.</li>
              <li><strong>Inheritance Depth:</strong> Deeper inheritance trees generally imply higher complexity and testing effort.</li>
            </ul>
            <p className="note">
               <ShieldCheck size={16} className="inline-icon" />
               These structural metrics are mapped to effort hours using calibrated industry benchmarks.
            </p>
          </div>
        </section>

        <section className="about-section">
          <h2>Trust & Defensibility</h2>
          <p>
            Estimates generated by this tool are completely transparent. In the result workspace, you can drill down into exactly how every hour was calculated. This allows project managers and developers to defend their timelines with data.
          </p>
        </section>
      </div>
    </div>
  );
};
